compilers:
  - name: opt_gas
    queue:
      host: queue_optimization_gas
      port: 5672
    exec_params:
      optimization: gas
  - name: opt_codesize
    queue:
      host: queue_optimization_codesize
      port: 5672
    exec_params:
      optimization: codesize
db:
  host: mongodb
  port: 27017
input_strategies: [1, 2]
# for logging level reference https://docs.python.org/3/library/logging.html#logging-levels
verbosity: DEBUG
use_queue: False